services:
  db:
    image: postgres:15
    container_name: order_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - order_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${DB_NAME} -U ${DB_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  order-service:
    build:
      context: ./
    container_name: order-service
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - order_network
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pg_data:

networks:
  order_network:
    driver: bridge
