services:
  db:
    image: postgres:14
    container_name: order_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: order_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - order_network


volumes:
  pg_data:

networks:
  order_network:
    driver: bridge
