app:
  name: "order-service"
  port: 8080

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}

auth:
  jwt_secret: ${JWT_SECRET}
  token_expiry: "24h"

logging:
  level: "info"
  file: "logs/app.log"

cache:
  enabled: true
  ttl: 60 # time-to-live in seconds
