app:
  name: "order-service"
  port: ${APP_PORT}

database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  name: ${DB_NAME}
  ssl_mode: ${DB_SSL_MODE}

kafka:
  address: ${KAFKA_ADDRESS}
  topic_order_status_changed: ${TOPIC_NAME}
